### ISSUE TITLE
No source code of sd_update

### ISSUE THREAD

**Issue by zetalog** [friendlyarm/sd-fuse_h5#1]
The fusing.sh script required root privilege.
I granted the privilege request because the script should be able to access /dev/sdX.
To my surprise, it didn't invoke system utilities like mkfs, dd, but invoked an executable released in this project: tools/sd_update.

This hurts users security volunability as we users couldn't find any opened source code of this utility. And this utility indeed looks like a worm due to its disassembly result.

Please open the source code of sd_update, or change its invocation to script implementation which should invoke tools that released by the distro vendors.

Thanks.

**Comment by friendlyarm** [comment]
you have every right to be afraid, but you can use the strace command to track all the behavior of the sd_update program.
